// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  production: false,
  slides: [
    { name: 'home', showHeader: false, showFooter: false },
    { name: 'about-me', showHeader: true, showFooter: true },
    { name: 'conquete-history-1', showHeader: true, showFooter: true },
    { name: 'conquete-history-2', showHeader: true, showFooter: true },
    { name: 'conquete-history-3', showHeader: true, showFooter: true },
    { name: 'conquete-history-4', showHeader: true, showFooter: true },
    { name: 'conquete-history-5', showHeader: true, showFooter: true },
    { name: 'conquete-history-6', showHeader: true, showFooter: true },
    { name: 'conquete-history-7', showHeader: true, showFooter: true },
    { name: 'conquete-history-8', showHeader: true, showFooter: true },
    { name: 'conquete-history-9', showHeader: true, showFooter: true },
    { name: 'conquete-history-10', showHeader: true, showFooter: true },
    { name: 'conquete-history-11', showHeader: true, showFooter: true },
    { name: 'conquete-history-12', showHeader: true, showFooter: true },
    { name: 'conquete-history-13', showHeader: true, showFooter: true },
    { name: 'conquete-history-14', showHeader: true, showFooter: true },
    { name: 'conquete-history-15', showHeader: true, showFooter: true },
    { name: 'conquete-history-16', showHeader: true, showFooter: true },
    { name: 'container-1', showHeader: true, showFooter: true },
    { name: 'container-2', showHeader: true, showFooter: true },
    { name: 'container-3', showHeader: true, showFooter: true },
    { name: 'container-4', showHeader: true, showFooter: true },
    { name: 'container-5', showHeader: true, showFooter: true },
    { name: 'container-6', showHeader: true, showFooter: true },
    { name: 'container-7', showHeader: true, showFooter: true },
    { name: 'container-8', showHeader: true, showFooter: true },
    { name: 'container-9', showHeader: true, showFooter: true },
    { name: 'container-10', showHeader: true, showFooter: true },
    { name: 'oci-1', showHeader: true, showFooter: true },
    { name: 'oci-2', showHeader: true, showFooter: true },
    { name: 'moby', showHeader: true, showFooter: true },
    { name: 'return-1', showHeader: true, showFooter: true },
    { name: 'devops-1', showHeader: true, showFooter: true },
    { name: 'devops-2', showHeader: true, showFooter: true },
    { name: 'devops-3', showHeader: true, showFooter: true },
    { name: 'devops-4', showHeader: true, showFooter: true },
    { name: 'devops-5', showHeader: true, showFooter: true },
    { name: 'agility-1', showHeader: true, showFooter: true },
    { name: 'agility-2', showHeader: true, showFooter: true },
    { name: 'agility-3', showHeader: true, showFooter: true },
    { name: 'agility-4', showHeader: true, showFooter: true },
    { name: 'agility-5', showHeader: true, showFooter: true },
    { name: 'container-4', showHeader: true, showFooter: true },
    { name: 'container-5', showHeader: true, showFooter: true },
    { name: 'norme-1', showHeader: true, showFooter: true },
    { name: 'norme-2', showHeader: true, showFooter: true },
    { name: 'rkt-1', showHeader: true, showFooter: true },
    { name: 'rkt-2', showHeader: true, showFooter: true },
    { name: 'rkt-3', showHeader: true, showFooter: true },
    { name: 'orchestrateur-1', showHeader: true, showFooter: true },
    { name: 'orchestrateur-2', showHeader: true, showFooter: true },
    { name: 'orchestrateur-3', showHeader: true, showFooter: true },
    { name: 'orchestrateur-4', showHeader: true, showFooter: true },
    { name: 'demo', showHeader: true, showFooter: true },
    { name: 'questions', showHeader: true, showFooter: true },
    { name: 'end', showHeader: true, showFooter: true }
  ]
};