export const environment = {
  production: true,
  slides: [
    { name: 'home', showHeader: false, showFooter: false },
    { name: 'about-me', showHeader: true, showFooter: true },
    { name: 'conquete-history-1', showHeader: true, showFooter: true },
    { name: 'conquete-history-2', showHeader: true, showFooter: true },
    { name: 'conquete-history-3', showHeader: true, showFooter: true },
    { name: 'conquete-history-4', showHeader: true, showFooter: true },
    { name: 'conquete-history-5', showHeader: true, showFooter: true },
    { name: 'container-1', showHeader: true, showFooter: true },
    { name: 'container-2', showHeader: true, showFooter: true },
    { name: 'container-3', showHeader: true, showFooter: true },
    { name: 'return-1', showHeader: true, showFooter: true },
    { name: 'devops-1', showHeader: true, showFooter: true },
    { name: 'devops-2', showHeader: true, showFooter: true },
    { name: 'devops-3', showHeader: true, showFooter: true },
    { name: 'devops-4', showHeader: true, showFooter: true },
    { name: 'devops-5', showHeader: true, showFooter: true },
    { name: 'agility-1', showHeader: true, showFooter: true },
    { name: 'agility-2', showHeader: true, showFooter: true },
    { name: 'agility-3', showHeader: true, showFooter: true },
    { name: 'agility-4', showHeader: true, showFooter: true },
    { name: 'agility-5', showHeader: true, showFooter: true },
    { name: 'container-4', showHeader: true, showFooter: true },
    { name: 'container-5', showHeader: true, showFooter: true },
    { name: 'norme-1', showHeader: true, showFooter: true },
    { name: 'norme-2', showHeader: true, showFooter: true },
    { name: 'rkt-1', showHeader: true, showFooter: true },
    { name: 'rkt-2', showHeader: true, showFooter: true },
    { name: 'rkt-3', showHeader: true, showFooter: true },
    { name: 'orchestrateur-1', showHeader: true, showFooter: true },
    { name: 'orchestrateur-2', showHeader: true, showFooter: true },
    { name: 'orchestrateur-3', showHeader: true, showFooter: true },
    { name: 'orchestrateur-4', showHeader: true, showFooter: true },
    { name: 'demo', showHeader: true, showFooter: true },
    { name: 'questions', showHeader: true, showFooter: true },
    { name: 'end', showHeader: true, showFooter: true }
  ]
};
